### PR TITLE
fix Cannot access protected property $contentType

### PR DESCRIPTION
**Pull request by mikenowak**
Cannot access protected property PhpMimeMailParser\Attachment::$contentType

### CODE REVIEW

**Comment by kruisdraad** [comment]
Another nice find indeed, was updated in abuseio-core but not in this module.

**Comment by mikenowak** [comment]
@kruisdraad, thanks.

Also, it doesn't appear that the `composer.json` was updated when `parser-common` was updated, would you be able to fix this?

**Comment by kruisdraad** [comment]
This is done manually and just push this new tag.

**Comment by mikenowak** [comment]
Should be done in #2

**Pull request merged**
